---
# created from docker cli at https://www.composerize.com/
# docker run --rm --name catalog-service -p 8080:9001 catalog-service:0.0.1-SNAPSHOT
version: '3.8'
services:
  catalog-service:
    depends_on:
      postgresql:
        condition: service_started
    container_name: catalog-service
    ports:
      - '9001:9001'
      - '8001:8001'
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog

    image: 'ghcr.io/wjc-van-es/catalog-service:0.0.4-SNAPSHOT'

  postgresql:
    container_name: polar-postgres
    environment:
      - POSTGRES_DB=polardb_catalog
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - polar-postgres:/var/lib/postgresql/data
    image: 'postgres:15.4' # version 16.1 is pulled, but not compatible with the data files

volumes:
  polar-postgres: