---
# created from docker cli at https://www.composerize.com/
# docker run --rm --name catalog-service -p 8080:9001 catalog-service:0.0.1-SNAPSHOT
version: '3.3'
services:
  catalog-service:
    container_name: catalog-service
    ports:
      - '8080:9001'
    image: 'catalog-service:0.0.1-SNAPSHOT'

  postgresql:
    container_name: polar-postgres
    environment:
      - POSTGRES_DB=polardb_catalog
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - 'polar-postgres:/var/lib/postgresql/data'
    image: 'postgres:15.3'

volumes:
  polar-postgres: